import { CourseType } from "@/types/CourseType";

export const coursesData: CourseType[] = [
  {
    _id: "course-1",
    title: "Foundations of Christian Faith",
    shortDescription: "Core Christian beliefs and biblical foundations",
    thumbnail: "/images/courses/img-1.png",
    instructor: {
      name: "Dr. Christian Foundation",
    },
    totalLearners: 2450,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "foundations-of-christian-faith" },
    level: "Beginner",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-2",
    title: "Old Testament History & Wisdom",
    shortDescription: "Old Testament narratives and biblical wisdom",
    thumbnail: "/images/courses/img-2.png",
    instructor: {
      name: "Dr. Biblical Scholar",
    },
    totalLearners: 1980,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "old-testament-history-wisdom" },
    level: "Intermediate",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-3",
    title: "New Testament & Gospel Teaching",
    shortDescription: "Jesus Christ and apostolic teachings",
    thumbnail: "/images/courses/img-3.png",
    instructor: {
      name: "Dr. Gospel Teacher",
    },
    totalLearners: 3120,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "new-testament-gospel-teaching" },
    level: "Beginner to Intermediate",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-4",
    title: "Christian Theology & Doctrine",
    shortDescription: "Systematic Christian theology",
    thumbnail: "/images/courses/img-4.png",
    instructor: {
      name: "Dr. Theologian",
    },
    totalLearners: 1650,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "christian-theology-doctrine" },
    level: "Advanced",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-5",
    title: "Prayer, Worship & Spiritual Life",
    shortDescription: "Spiritual practices and personal growth",
    thumbnail: "/images/courses/img-1.png",
    instructor: {
      name: "Dr. Spiritual Guide",
    },
    totalLearners: 2890,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "prayer-worship-spiritual-life" },
    level: "Intermediate",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-6",
    title: "Christian Ethics & Living",
    shortDescription: "Biblical ethics and Christian living",
    thumbnail: "/images/courses/img-2.png",
    instructor: {
      name: "Dr. Ethics Scholar",
    },
    totalLearners: 2010,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "christian-ethics-living" },
    level: "Intermediate",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
  {
    _id: "course-7",
    title: "Church History & Missions",
    shortDescription: "Church history and Christian missions",
    thumbnail: "/images/courses/img-3.png",
    instructor: {
      name: "Dr. Church Historian",
    },
    totalLearners: 1540,
    isCertificationProvide: true,
    price: 99,
    discountPrice: 79,
    status: "Ongoing",
    slug: { current: "church-history-missions" },
    level: "Intermediate",
    overview: [],
    duration: 350,
    lessonsCount: 70,
  },
];
