<?php
defined('MOODLE_INTERNAL') || die();

$functions = array(
    'local_skillsaint_get_all_site_data' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_all_site_data',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all site-wide configuration (Home, About, Programs)',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> '',
    ),
    'local_skillsaint_save_application' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'save_application',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Save or update a student application before payment',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> '',
    ),
    'local_skillsaint_confirm_payment' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'confirm_payment',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Finalize payment and enroll user',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> '',
    ),
    'local_skillsaint_activate_account' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'activate_account',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Activate account using code',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> '',
    ),
    'local_skillsaint_check_activation' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'check_activation',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Check if account is activated',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> '',
    ),
    'local_skillsaint_get_admin_dashboard_stats' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_admin_dashboard_stats',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get live admin dashboard statistics from Moodle DB',
        'type'        => 'read',
        'ajax'        => true,
    ),
    'local_skillsaint_get_all_admin_users' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_all_admin_users',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all Moodle users for admin management',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_all_paid_applications' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_all_paid_applications',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all paid applications for finance page',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_create_course' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'create_course',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Create a new course',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_update_course' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'update_course',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Update a course',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_delete_course' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'delete_course',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Delete a course',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_rename_section' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'rename_section',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Rename a course section',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_add_section' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'add_section',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Add a new section to a course',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_add_module' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'add_module',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Add a new module to a course section',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_update_module_content' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'update_module_content',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Update the HTML content of a page module',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_delete_section' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'delete_section',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Delete a course section and all its modules',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_module_content' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_module_content',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get the HTML content of a page module',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_courses_full' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_courses_full',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all courses with full metadata including visibility and files',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_exams' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_exams',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all quizzes from all courses',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_create_question' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'create_question',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Create a multichoice question in a quiz',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_delete_question' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'delete_question',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Delete a question from a quiz',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_init_exam' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'init_exam',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Initialize a quiz in a course',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_quiz_questions' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_quiz_questions',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all questions for a specific quiz',
        'type'        => 'read',
        'ajax'        => true,
    ),
    'local_skillsaint_reorder_questions' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'reorder_questions',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Reorder questions in a quiz',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_update_question' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'update_question',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Update an existing multichoice question',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_save_site_data' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'save_site_data',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Save all site content data',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_student_dashboard_data' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_student_dashboard_data',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get enrolled courses and personalized dashboard info for student',
        'type'        => 'read',
        'ajax'        => true,
    ),
    // ---- Inquiry / Support Ticket System ----
    'local_skillsaint_send_inquiry' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'send_inquiry',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Student sends a support inquiry linked to a specific course',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_get_all_inquiries' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_all_inquiries',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Admin: get all student inquiries with filtering',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_reply_inquiry' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'reply_inquiry',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Admin: reply to a student inquiry',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
    'local_skillsaint_get_student_inquiries' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_student_inquiries',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Student: get own inquiries and admin replies',
        'type'        => 'read',
        'ajax'        => true,
    ),
    // ---- Avatar Upload ----
    'local_skillsaint_update_avatar' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'update_avatar',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Update user profile picture from Base64 image',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_add_inquiry_message' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'add_inquiry_message',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Add a message to an existing support thread',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_delete_inquiry' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'delete_inquiry',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Delete an inquiry thread and all its messages',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_get_course_curriculum' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_course_curriculum',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get course sections and modules with exam authorization status',
        'type'        => 'read',
        'ajax'        => true,
    ),
    'local_skillsaint_authorize_exam' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'authorize_exam',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Grant or revoke exam authorization for a student',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config'
    ),
    'local_skillsaint_update_student_profile' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'update_student_profile',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Update student profile fields',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_change_password' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'change_password',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Securely change student password',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_setup_initial_password' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'setup_initial_password',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Set initial password for new students (replaces default temp password)',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_save_exam_result' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'save_exam_result',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Save student exam score and attempt metadata',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'local_skillsaint_get_all_results' => array(
        'classname'   => 'local_skillsaint_external',
        'methodname'  => 'get_all_results',
        'classpath'   => 'local/skillsaint/externallib.php',
        'description' => 'Get all student exam results for admin view',
        'type'        => 'read',
        'ajax'        => true,
        'capabilities'=> 'moodle/site:config',
    ),
);

$services = array(
    'Skillsaint Core Services' => array(
        'functions' => array(
            'local_skillsaint_get_all_site_data',
            'local_skillsaint_save_application',
            'local_skillsaint_confirm_payment',
            'local_skillsaint_activate_account',
            'local_skillsaint_check_activation',
            'local_skillsaint_get_admin_dashboard_stats',
            'local_skillsaint_get_all_admin_users',
            'local_skillsaint_get_all_paid_applications',
            'local_skillsaint_create_course',
            'local_skillsaint_update_course',
            'local_skillsaint_delete_course',
            'local_skillsaint_rename_section',
            'local_skillsaint_add_section',
            'local_skillsaint_add_module',
            'local_skillsaint_get_courses_full',
            'local_skillsaint_get_exams',
            'local_skillsaint_create_question',
            'local_skillsaint_delete_question',
            'local_skillsaint_init_exam',
            'local_skillsaint_get_quiz_questions',
            'local_skillsaint_reorder_questions',
            'local_skillsaint_update_question',
            'local_skillsaint_save_site_data',
            'local_skillsaint_get_student_dashboard_data',
            'local_skillsaint_send_inquiry',
            'local_skillsaint_get_all_inquiries',
            'local_skillsaint_reply_inquiry',
            'local_skillsaint_get_student_inquiries',
            'local_skillsaint_update_avatar',
            'local_skillsaint_add_inquiry_message',
            'local_skillsaint_delete_inquiry',
            'local_skillsaint_update_student_profile',
            'local_skillsaint_change_password',
            'local_skillsaint_setup_initial_password',
            'local_skillsaint_save_exam_result',
            'local_skillsaint_get_all_results',
        ),
        'restrictedusers' => 0,
        'enabled' => 1,
    ),
    'Skillsaint Management API' => array(
        'functions' => array(
            'local_skillsaint_rename_section',
            'local_skillsaint_add_section',
            'local_skillsaint_delete_course',
            'local_skillsaint_update_course',
            'local_skillsaint_add_module',
        ),
        'restrictedusers' => 0,
        'enabled' => 1,
    )
);
